apiVersion: v1
kind: Pod
metadata:
  name: thefakesite-pod
  labels:
    name: thefakesite
    app: thefakesite
spec:
  containers:
    - name: thefakesite
      image: pearlyna/thefakesite:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8000
      securityContext:
        runAsUser: 4000
      env:
        - name: BACKEND_API
          value: http://thefakeapi-service.default.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: thefakeapi-pod
  labels:
    name: thefakeapi
    app: thefakeapi
spec:
  containers:
    - name: thefakeapi
      image: pearlyna/thefakeapi:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /thefakeapi
          port: 3000
        periodSeconds: 30
      securityContext:
        runAsUser: 4000
      env:
        - name: MONGODB_STR
          value: mongodb://user:pass@mongodb-service.default.svc.cluster.local:27017
        - name: PORT
          value: "3000"
        - name: APITOKEN
          value: itsjustatokensir
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    name: mongodb
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongodb/mongodb-community-server
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass
      resources:
        limits:
          memory: "500Mi"
          cpu: "1"
      ports:
        - containerPort: 27017