name: pipeline

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Login Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: cd backend && docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/thefakeapi:${{ github.ref_name }}
      
    - name: Push image to repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thefakeapi:${{ github.ref_name }}
