name: pipeline

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Login Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image for backend
      run: cd backend && docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/thefakeapi:${{ github.ref_name }}
    
    - name: Build the Docker image for frontend
      run: cd ../frontend && docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/thefakesite:${{ github.ref_name }}
     
    - name: Push backend image to repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thefakeapi:${{ github.ref_name }}

    - name: Push frontend image to repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thefakesite:${{ github.ref_name }}
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    - run: npm i
    - run: npm test
